#!/bin/bash

## call this file as
##   sbatch --job-name=oracle_exp1_p_sgn_nx_ny sbatch_oracle_exp1 p sgn nx ny

#SBATCH --ntasks=168
##SBATCH --job-name=KLIEP_exp1
#SBATCH --partition=broadwl
#SBATCH --time=1-12:00:00

module load parallel
module load hdf5

parallel --delay .2 -j $SLURM_NTASKS --joblog __$SLURM_JOB_NAME.runtask.log --resume srun --exclusive -N1 -n1 --error=/scratch/midway2/mkolar/output/$SLURM_JOB_NAME.err.{1} --output=/scratch/midway2/mkolar/output/$SLURM_JOB_NAME.out.{1} /home/mkolar/project-midway/julia-1.0.1/bin/julia experiment1.jl ${1} ${2} ${3} ${4} {1} ::: {1..1000}
