#!/bin/bash

#SBATCH --ntasks=112
#SBATCH --partition=broadwl
#SBATCH --time=1-12:00:00

module load parallel
module load hdf5

parallel -j $SLURM_NTASKS --joblog __$SLURM_JOB_NAME.runtask.log --resume srun --exclusive -N1 -n1 --error=/scratch/midway2/mkolar/output/$SLURM_JOB_NAME.err.{1} --output=/scratch/midway2/mkolar/output/$SLURM_JOB_NAME.out.{1} /home/mkolar/project-midway/julia-1.0.1/bin/julia experiment2.jl ${1} ${2} ${3} ${4} ${5} ${6} {1} ::: {1..1000}

