#!/bin/bash

## call this file as
##   sbatch --job-name=exp4_m_sgn sbatch_exp4 m sgn numChanges lbInd

#SBATCH --partition=cpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=25
#SBATCH --time=1-12:00:00
#SBATCH --mem=128000M

parallel --delay .2 -j 25 --joblog __$SLURM_JOB_NAME.runtask.log  /mnt/storage/home/sl9885/julia-1.5.4/bin/julia experiment4.jl ${1} ${2} ${3} ${4} {1} ${5} ::: {1..1000}
