#!/bin/bash

## call this file as
##   sbatch --job-name=exp4_m_sgn sbatch_exp4 m sgn numChanges lbInd

#SBATCH --partition=cpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --time=1-12:00:00

parallel --delay .2 -j 16 --joblog __$SLURM_JOB_NAME.runtask.log  julia experiment4.jl ${1} ${2} ${3} ${4} {1} ::: {1..16}
